// Regenerates src/lib/agent/prompts/_inline.ts from the .md prompt files.
// Run before every build so the Vercel serverless bundle always has the
// freshest prompt layers (the .md files are the canonical source; the
// inlined TS module is the bundled fallback for read-only filesystems).
import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')
const promptsDir = join(root, 'src', 'lib', 'agent', 'prompts')

const layers = ['role', 'workflow', 'governance', 'tools']
const parts = [
  '// AUTO-GENERATED by scripts/gen-prompts.mjs — do not edit by hand.',
  '// Keeps the prompt layers bundled into the Vercel serverless function',
  '// so the agent can assemble its system prompt even when the filesystem',
  '// is read-only (Vercel /var/task has no src/ tree). Regenerated from',
  '// the .md files before every build (prebuild script in package.json).',
  '',
  'export const PROMPT_LAYERS_INLINE: Record<string, string> = {',
]
for (const layer of layers) {
  const content = readFileSync(join(promptsDir, `${layer}.md`), 'utf8').replace(/\s+$/, '')
  parts.push(`  ${JSON.stringify(layer)}: ${JSON.stringify(content)},`)
}
parts.push('};')
parts.push('')
writeFileSync(join(promptsDir, '_inline.ts'), parts.join('\n'), 'utf8')
console.log(`[gen-prompts] wrote ${layers.length} layers to _inline.ts`)
